services:
  kurup:
    image: ghcr.io/davistdaniel/kurup:latest
    container_name: kurup
    ports:
      - "9494:9494"
    volumes:
      - ./notes:/app/notes # make sure the notes folder exists before running the container‚ otherwise the folder will be owned by root.
      # you can also use a custom path for the notes directory
      #- /home/yourusername/Documents/notes:/app/notes                        
    command: ["--notes_dir", "/app/notes"]
    user: "1000:1000" # set to your own local UID:GID, run `id -u` to find UID and run `id -g` to find GID