services:
  kurup:
    image: ghcr.io/davistdaniel/kurup:latest
    container_name: kurup
    ports:
      - "9494:9494"
    volumes:
      - ./notes:/app/notes
    command: ["--notes_dir", "notes", "--port", "9494"]
